"""add date to plan

Revision ID: 23627ae07048
Revises: 6dddd54ee317
Create Date: 2023-11-21 10:37:10.478543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23627ae07048'
down_revision: Union[str, None] = '6dddd54ee317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('plan_date', sa.DateTime(), nullable=True))
    op.alter_column('plan', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('plan', 'plan_date')
    # ### end Alembic commands ###
